#ifndef __INCL_FONTDEF__
#define __INCL_FONTDEF__

#define LCDFONT_INCLUDE_FONT_5x7
#define LCDFONT_INCLUDE_FONT_6x8
#define LCDFONT_INCLUDE_FONT_8x16

#define LCDFONT_INCLUDE_FONT_6x8_16
#define LCDFONT_INCLUDE_FONT_7x10
#define LCDFONT_INCLUDE_FONT_11x18
#define LCDFONT_INCLUDE_FONT_16x26
#define LCDFONT_INCLUDE_FONT_16x24

#define USE_GEOMETRIC 0

#endif
